### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by bshoults** [craftcms/redactor-clips#6]
I'm getting an error after installing and including clips on a toolbar. 

```
Uncaught TypeError: this.modal.createCancelButton is not a function
```

It's pointing to line 44  in clips.js

```
this.modal.createCancelButton();
```

Craft Pro 2.5.2759

**Comment by joleksow** [comment]
I'm running into the same issue.  I was able to get it working by changing that line to 
```javascript
this.modal.getCancelButton();
```
Not sure if this is the actual expected results.

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/redactor-clips/commit/f8778b3fcd8bed1ffa1b00a1e810845db0059260
